# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CH_BL14B1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_BL14B1(object):
    def setupUi(self, Form_BL14B1):
        Form_BL14B1.setObjectName("Form_BL14B1")
        Form_BL14B1.resize(350, 240)
        self.frame_4 = QtWidgets.QFrame(Form_BL14B1)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 331, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.BL14_ch1 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch1.setGeometry(QtCore.QRect(20, 10, 45, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.BL14_ch1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch1.setFont(font)
        self.BL14_ch1.setObjectName("BL14_ch1")
        self.BL14_ch2 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch2.setGeometry(QtCore.QRect(20, 45, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch2.setFont(font)
        self.BL14_ch2.setObjectName("BL14_ch2")
        self.BL14_ch3 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch3.setGeometry(QtCore.QRect(20, 80, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch3.setFont(font)
        self.BL14_ch3.setObjectName("BL14_ch3")
        self.BL14_ch6 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch6.setGeometry(QtCore.QRect(20, 185, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch6.setFont(font)
        self.BL14_ch6.setObjectName("BL14_ch6")
        self.BL14_ch4 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch4.setGeometry(QtCore.QRect(20, 115, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch4.setFont(font)
        self.BL14_ch4.setObjectName("BL14_ch4")
        self.BL14_ch5 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch5.setGeometry(QtCore.QRect(20, 150, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch5.setFont(font)
        self.BL14_ch5.setObjectName("BL14_ch5")
        self.BL14_ch9 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch9.setGeometry(QtCore.QRect(70, 80, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch9.setFont(font)
        self.BL14_ch9.setObjectName("BL14_ch9")
        self.BL14_ch8 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch8.setGeometry(QtCore.QRect(70, 45, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch8.setFont(font)
        self.BL14_ch8.setObjectName("BL14_ch8")
        self.BL14_ch7 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch7.setGeometry(QtCore.QRect(70, 10, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch7.setFont(font)
        self.BL14_ch7.setObjectName("BL14_ch7")
        self.BL14_ch10 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch10.setGeometry(QtCore.QRect(70, 115, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch10.setFont(font)
        self.BL14_ch10.setObjectName("BL14_ch10")
        self.BL14_ch12 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch12.setGeometry(QtCore.QRect(70, 185, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch12.setFont(font)
        self.BL14_ch12.setObjectName("BL14_ch12")
        self.BL14_ch11 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch11.setGeometry(QtCore.QRect(70, 150, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch11.setFont(font)
        self.BL14_ch11.setObjectName("BL14_ch11")
        self.BL14_ch13 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch13.setGeometry(QtCore.QRect(120, 10, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch13.setFont(font)
        self.BL14_ch13.setObjectName("BL14_ch13")
        self.BL14_ch14 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch14.setGeometry(QtCore.QRect(120, 45, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch14.setFont(font)
        self.BL14_ch14.setObjectName("BL14_ch14")
        self.BL14_ch15 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch15.setGeometry(QtCore.QRect(120, 80, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch15.setFont(font)
        self.BL14_ch15.setObjectName("BL14_ch15")
        self.BL14_ch16 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch16.setGeometry(QtCore.QRect(120, 115, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch16.setFont(font)
        self.BL14_ch16.setObjectName("BL14_ch16")
        self.BL14_ch17 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch17.setGeometry(QtCore.QRect(120, 150, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch17.setFont(font)
        self.BL14_ch17.setObjectName("BL14_ch17")
        self.BL14_ch18 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch18.setGeometry(QtCore.QRect(120, 185, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch18.setFont(font)
        self.BL14_ch18.setObjectName("BL14_ch18")
        self.BL14_ch19 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch19.setGeometry(QtCore.QRect(170, 10, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch19.setFont(font)
        self.BL14_ch19.setObjectName("BL14_ch19")
        self.BL14_ch20 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch20.setGeometry(QtCore.QRect(170, 45, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch20.setFont(font)
        self.BL14_ch20.setObjectName("BL14_ch20")
        self.BL14_ch22 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch22.setGeometry(QtCore.QRect(170, 115, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch22.setFont(font)
        self.BL14_ch22.setObjectName("BL14_ch22")
        self.BL14_ch21 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch21.setGeometry(QtCore.QRect(170, 80, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch21.setFont(font)
        self.BL14_ch21.setObjectName("BL14_ch21")
        self.BL14_ch23 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch23.setGeometry(QtCore.QRect(170, 150, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch23.setFont(font)
        self.BL14_ch23.setObjectName("BL14_ch23")
        self.BL14_ch24 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch24.setGeometry(QtCore.QRect(170, 185, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch24.setFont(font)
        self.BL14_ch24.setObjectName("BL14_ch24")
        self.BL14_ch26 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch26.setGeometry(QtCore.QRect(220, 45, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch26.setFont(font)
        self.BL14_ch26.setObjectName("BL14_ch26")
        self.BL14_ch27 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch27.setGeometry(QtCore.QRect(220, 80, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch27.setFont(font)
        self.BL14_ch27.setObjectName("BL14_ch27")
        self.BL14_ch28 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch28.setGeometry(QtCore.QRect(220, 115, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch28.setFont(font)
        self.BL14_ch28.setObjectName("BL14_ch28")
        self.BL14_ch25 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch25.setGeometry(QtCore.QRect(220, 10, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch25.setFont(font)
        self.BL14_ch25.setObjectName("BL14_ch25")
        self.BL14_ch30 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch30.setGeometry(QtCore.QRect(220, 185, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch30.setFont(font)
        self.BL14_ch30.setObjectName("BL14_ch30")
        self.BL14_ch29 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch29.setGeometry(QtCore.QRect(220, 150, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch29.setFont(font)
        self.BL14_ch29.setObjectName("BL14_ch29")
        self.BL14_ch36 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch36.setGeometry(QtCore.QRect(270, 185, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch36.setFont(font)
        self.BL14_ch36.setObjectName("BL14_ch36")
        self.BL14_ch34 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch34.setGeometry(QtCore.QRect(270, 115, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch34.setFont(font)
        self.BL14_ch34.setObjectName("BL14_ch34")
        self.BL14_ch33 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch33.setGeometry(QtCore.QRect(270, 80, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch33.setFont(font)
        self.BL14_ch33.setObjectName("BL14_ch33")
        self.BL14_ch31 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch31.setGeometry(QtCore.QRect(270, 10, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch31.setFont(font)
        self.BL14_ch31.setObjectName("BL14_ch31")
        self.BL14_ch35 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch35.setGeometry(QtCore.QRect(270, 150, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch35.setFont(font)
        self.BL14_ch35.setObjectName("BL14_ch35")
        self.BL14_ch32 = QtWidgets.QCheckBox(self.frame_4)
        self.BL14_ch32.setGeometry(QtCore.QRect(270, 45, 45, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL14_ch32.setFont(font)
        self.BL14_ch32.setObjectName("BL14_ch32")

        self.retranslateUi(Form_BL14B1)
        QtCore.QMetaObject.connectSlotsByName(Form_BL14B1)

    def retranslateUi(self, Form_BL14B1):
        _translate = QtCore.QCoreApplication.translate
        Form_BL14B1.setWindowTitle(_translate("Form_BL14B1", "Form"))
        self.BL14_ch1.setText(_translate("Form_BL14B1", "0"))
        self.BL14_ch2.setText(_translate("Form_BL14B1", "1"))
        self.BL14_ch3.setText(_translate("Form_BL14B1", "2"))
        self.BL14_ch6.setText(_translate("Form_BL14B1", "5"))
        self.BL14_ch4.setText(_translate("Form_BL14B1", "3"))
        self.BL14_ch5.setText(_translate("Form_BL14B1", "4"))
        self.BL14_ch9.setText(_translate("Form_BL14B1", "8"))
        self.BL14_ch8.setText(_translate("Form_BL14B1", "7"))
        self.BL14_ch7.setText(_translate("Form_BL14B1", "6"))
        self.BL14_ch10.setText(_translate("Form_BL14B1", "9"))
        self.BL14_ch12.setText(_translate("Form_BL14B1", "11"))
        self.BL14_ch11.setText(_translate("Form_BL14B1", "10"))
        self.BL14_ch13.setText(_translate("Form_BL14B1", "12"))
        self.BL14_ch14.setText(_translate("Form_BL14B1", "13"))
        self.BL14_ch15.setText(_translate("Form_BL14B1", "14"))
        self.BL14_ch16.setText(_translate("Form_BL14B1", "15"))
        self.BL14_ch17.setText(_translate("Form_BL14B1", "16"))
        self.BL14_ch18.setText(_translate("Form_BL14B1", "17"))
        self.BL14_ch19.setText(_translate("Form_BL14B1", "18"))
        self.BL14_ch20.setText(_translate("Form_BL14B1", "19"))
        self.BL14_ch22.setText(_translate("Form_BL14B1", "21"))
        self.BL14_ch21.setText(_translate("Form_BL14B1", "20"))
        self.BL14_ch23.setText(_translate("Form_BL14B1", "22"))
        self.BL14_ch24.setText(_translate("Form_BL14B1", "23"))
        self.BL14_ch26.setText(_translate("Form_BL14B1", "25"))
        self.BL14_ch27.setText(_translate("Form_BL14B1", "26"))
        self.BL14_ch28.setText(_translate("Form_BL14B1", "27"))
        self.BL14_ch25.setText(_translate("Form_BL14B1", "24"))
        self.BL14_ch30.setText(_translate("Form_BL14B1", "29"))
        self.BL14_ch29.setText(_translate("Form_BL14B1", "28"))
        self.BL14_ch36.setText(_translate("Form_BL14B1", "35"))
        self.BL14_ch34.setText(_translate("Form_BL14B1", "33"))
        self.BL14_ch33.setText(_translate("Form_BL14B1", "32"))
        self.BL14_ch31.setText(_translate("Form_BL14B1", "30"))
        self.BL14_ch35.setText(_translate("Form_BL14B1", "34"))
        self.BL14_ch32.setText(_translate("Form_BL14B1", "31"))

