# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CH_BL36XU.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_BL36XU(object):
    def setupUi(self, Form_BL36XU):
        Form_BL36XU.setObjectName("Form_BL36XU")
        Form_BL36XU.resize(350, 240)
        self.frame_4 = QtWidgets.QFrame(Form_BL36XU)
        self.frame_4.setGeometry(QtCore.QRect(15, 20, 320, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.BL36XU_ch1 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch1.setGeometry(QtCore.QRect(20, 10, 41, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.BL36XU_ch1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch1.setFont(font)
        self.BL36XU_ch1.setObjectName("BL36XU_ch1")
        self.BL36XU_ch2 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch2.setGeometry(QtCore.QRect(20, 50, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch2.setFont(font)
        self.BL36XU_ch2.setObjectName("BL36XU_ch2")
        self.BL36XU_ch3 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch3.setGeometry(QtCore.QRect(20, 90, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch3.setFont(font)
        self.BL36XU_ch3.setObjectName("BL36XU_ch3")
        self.BL36XU_ch6 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch6.setGeometry(QtCore.QRect(80, 10, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch6.setFont(font)
        self.BL36XU_ch6.setObjectName("BL36XU_ch6")
        self.BL36XU_ch4 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch4.setGeometry(QtCore.QRect(20, 130, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch4.setFont(font)
        self.BL36XU_ch4.setObjectName("BL36XU_ch4")
        self.BL36XU_ch5 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch5.setGeometry(QtCore.QRect(20, 170, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch5.setFont(font)
        self.BL36XU_ch5.setObjectName("BL36XU_ch5")
        self.BL36XU_ch9 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch9.setGeometry(QtCore.QRect(80, 130, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch9.setFont(font)
        self.BL36XU_ch9.setObjectName("BL36XU_ch9")
        self.BL36XU_ch8 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch8.setGeometry(QtCore.QRect(80, 90, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch8.setFont(font)
        self.BL36XU_ch8.setObjectName("BL36XU_ch8")
        self.BL36XU_ch7 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch7.setGeometry(QtCore.QRect(80, 50, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch7.setFont(font)
        self.BL36XU_ch7.setObjectName("BL36XU_ch7")
        self.BL36XU_ch10 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch10.setGeometry(QtCore.QRect(80, 170, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch10.setFont(font)
        self.BL36XU_ch10.setObjectName("BL36XU_ch10")
        self.BL36XU_ch12 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch12.setGeometry(QtCore.QRect(140, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch12.setFont(font)
        self.BL36XU_ch12.setObjectName("BL36XU_ch12")
        self.BL36XU_ch11 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch11.setGeometry(QtCore.QRect(140, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch11.setFont(font)
        self.BL36XU_ch11.setObjectName("BL36XU_ch11")
        self.BL36XU_ch13 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch13.setGeometry(QtCore.QRect(140, 90, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch13.setFont(font)
        self.BL36XU_ch13.setObjectName("BL36XU_ch13")
        self.BL36XU_ch14 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch14.setGeometry(QtCore.QRect(140, 130, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch14.setFont(font)
        self.BL36XU_ch14.setObjectName("BL36XU_ch14")
        self.BL36XU_ch15 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch15.setGeometry(QtCore.QRect(140, 170, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch15.setFont(font)
        self.BL36XU_ch15.setObjectName("BL36XU_ch15")
        self.BL36XU_ch16 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch16.setGeometry(QtCore.QRect(200, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch16.setFont(font)
        self.BL36XU_ch16.setObjectName("BL36XU_ch16")
        self.BL36XU_ch17 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch17.setGeometry(QtCore.QRect(200, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch17.setFont(font)
        self.BL36XU_ch17.setObjectName("BL36XU_ch17")
        self.BL36XU_ch18 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch18.setGeometry(QtCore.QRect(200, 90, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch18.setFont(font)
        self.BL36XU_ch18.setObjectName("BL36XU_ch18")
        self.BL36XU_ch19 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch19.setGeometry(QtCore.QRect(200, 130, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch19.setFont(font)
        self.BL36XU_ch19.setObjectName("BL36XU_ch19")
        self.BL36XU_ch20 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch20.setGeometry(QtCore.QRect(200, 170, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch20.setFont(font)
        self.BL36XU_ch20.setObjectName("BL36XU_ch20")
        self.BL36XU_ch22 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch22.setGeometry(QtCore.QRect(260, 50, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch22.setFont(font)
        self.BL36XU_ch22.setObjectName("BL36XU_ch22")
        self.BL36XU_ch25 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch25.setGeometry(QtCore.QRect(260, 170, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch25.setFont(font)
        self.BL36XU_ch25.setObjectName("BL36XU_ch25")
        self.BL36XU_ch21 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch21.setGeometry(QtCore.QRect(260, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch21.setFont(font)
        self.BL36XU_ch21.setObjectName("BL36XU_ch21")
        self.BL36XU_ch23 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch23.setGeometry(QtCore.QRect(260, 90, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch23.setFont(font)
        self.BL36XU_ch23.setObjectName("BL36XU_ch23")
        self.BL36XU_ch24 = QtWidgets.QCheckBox(self.frame_4)
        self.BL36XU_ch24.setGeometry(QtCore.QRect(260, 130, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BL36XU_ch24.setFont(font)
        self.BL36XU_ch24.setObjectName("BL36XU_ch24")

        self.retranslateUi(Form_BL36XU)
        QtCore.QMetaObject.connectSlotsByName(Form_BL36XU)

    def retranslateUi(self, Form_BL36XU):
        _translate = QtCore.QCoreApplication.translate
        Form_BL36XU.setWindowTitle(_translate("Form_BL36XU", "Form"))
        self.BL36XU_ch1.setText(_translate("Form_BL36XU", "0"))
        self.BL36XU_ch2.setText(_translate("Form_BL36XU", "1"))
        self.BL36XU_ch3.setText(_translate("Form_BL36XU", "2"))
        self.BL36XU_ch6.setText(_translate("Form_BL36XU", "5"))
        self.BL36XU_ch4.setText(_translate("Form_BL36XU", "3"))
        self.BL36XU_ch5.setText(_translate("Form_BL36XU", "4"))
        self.BL36XU_ch9.setText(_translate("Form_BL36XU", "8"))
        self.BL36XU_ch8.setText(_translate("Form_BL36XU", "7"))
        self.BL36XU_ch7.setText(_translate("Form_BL36XU", "6"))
        self.BL36XU_ch10.setText(_translate("Form_BL36XU", "9"))
        self.BL36XU_ch12.setText(_translate("Form_BL36XU", "11"))
        self.BL36XU_ch11.setText(_translate("Form_BL36XU", "10"))
        self.BL36XU_ch13.setText(_translate("Form_BL36XU", "12"))
        self.BL36XU_ch14.setText(_translate("Form_BL36XU", "13"))
        self.BL36XU_ch15.setText(_translate("Form_BL36XU", "14"))
        self.BL36XU_ch16.setText(_translate("Form_BL36XU", "15"))
        self.BL36XU_ch17.setText(_translate("Form_BL36XU", "16"))
        self.BL36XU_ch18.setText(_translate("Form_BL36XU", "17"))
        self.BL36XU_ch19.setText(_translate("Form_BL36XU", "18"))
        self.BL36XU_ch20.setText(_translate("Form_BL36XU", "19"))
        self.BL36XU_ch22.setText(_translate("Form_BL36XU", "21"))
        self.BL36XU_ch25.setText(_translate("Form_BL36XU", "24"))
        self.BL36XU_ch21.setText(_translate("Form_BL36XU", "20"))
        self.BL36XU_ch23.setText(_translate("Form_BL36XU", "22"))
        self.BL36XU_ch24.setText(_translate("Form_BL36XU", "23"))

