# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SDD_7element.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 240)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(15, 20, 320, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.SDD_ch6 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch6.setGeometry(QtCore.QRect(110, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch6.setFont(font)
        self.SDD_ch6.setObjectName("SDD_ch6")
        self.SDD_ch7 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch7.setGeometry(QtCore.QRect(180, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch7.setFont(font)
        self.SDD_ch7.setObjectName("SDD_ch7")
        self.SDD_ch8 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch8.setGeometry(QtCore.QRect(110, 150, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch8.setFont(font)
        self.SDD_ch8.setObjectName("SDD_ch8")
        self.SDD_ch5 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch5.setGeometry(QtCore.QRect(210, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch5.setFont(font)
        self.SDD_ch5.setObjectName("SDD_ch5")
        self.SDD_ch2 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch2.setGeometry(QtCore.QRect(180, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch2.setFont(font)
        self.SDD_ch2.setObjectName("SDD_ch2")
        self.SDD_ch1 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch1.setGeometry(QtCore.QRect(110, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch1.setFont(font)
        self.SDD_ch1.setObjectName("SDD_ch1")
        self.SDD_ch3 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch3.setGeometry(QtCore.QRect(70, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch3.setFont(font)
        self.SDD_ch3.setObjectName("SDD_ch3")
        self.SDD_ch4 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch4.setGeometry(QtCore.QRect(140, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch4.setFont(font)
        self.SDD_ch4.setObjectName("SDD_ch4")
        self.SDD_ch9 = QtWidgets.QCheckBox(self.frame)
        self.SDD_ch9.setGeometry(QtCore.QRect(180, 150, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SDD_ch9.setFont(font)
        self.SDD_ch9.setObjectName("SDD_ch9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SDD_ch6.setText(_translate("Form", "6"))
        self.SDD_ch7.setText(_translate("Form", "7"))
        self.SDD_ch8.setText(_translate("Form", "8"))
        self.SDD_ch5.setText(_translate("Form", "5"))
        self.SDD_ch2.setText(_translate("Form", "2"))
        self.SDD_ch1.setText(_translate("Form", "1"))
        self.SDD_ch3.setText(_translate("Form", "3"))
        self.SDD_ch4.setText(_translate("Form", "4"))
        self.SDD_ch9.setText(_translate("Form", "9"))

