# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_pySSD_win_2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 743)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_4 = QtWidgets.QWidget(self.tab_3)
        self.widget_4.setGeometry(QtCore.QRect(30, 30, 801, 461))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(860, 490, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(1000, 490, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_5.setGeometry(QtCore.QRect(1060, 483, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(930, 488, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_3.setGeometry(QtCore.QRect(900, 60, 421, 361))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scrollArea_3.setFont(font)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 419, 359))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(1200, 11, 114, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(990, 522, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_10.setGeometry(QtCore.QRect(850, 520, 114, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_11.setGeometry(QtCore.QRect(1189, 572, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setGeometry(QtCore.QRect(1140, 483, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(960, 580, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 6, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setGeometry(QtCore.QRect(110, 6, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(840, 585, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(20, 520, 801, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 15, 201, 18))
        self.checkBox_3.setObjectName("checkBox_3")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_5.setGeometry(QtCore.QRect(180, 60, 611, 41))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_22.setGeometry(QtCore.QRect(20, 60, 131, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox.setGeometry(QtCore.QRect(490, 13, 91, 24))
        self.spinBox.setMaximum(300)
        self.spinBox.setProperty("value", 11)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_2.setGeometry(QtCore.QRect(690, 13, 61, 24))
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setProperty("value", 3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_7.setGeometry(QtCore.QRect(240, 13, 151, 26))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.label_34 = QtWidgets.QLabel(self.frame_4)
        self.label_34.setGeometry(QtCore.QRect(400, 20, 81, 16))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.frame_4)
        self.label_36.setGeometry(QtCore.QRect(600, 20, 71, 16))
        self.label_36.setObjectName("label_36")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(900, 430, 421, 41))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.rB_9809 = QtWidgets.QRadioButton(self.groupBox_11)
        self.rB_9809.setGeometry(QtCore.QRect(20, 10, 71, 18))
        self.rB_9809.setChecked(True)
        self.rB_9809.setObjectName("rB_9809")
        self.rB_DUBBLE_2 = QtWidgets.QRadioButton(self.groupBox_11)
        self.rB_DUBBLE_2.setGeometry(QtCore.QRect(110, 10, 71, 18))
        self.rB_DUBBLE_2.setObjectName("rB_DUBBLE_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 40, 481, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setGeometry(QtCore.QRect(510, 40, 431, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(106, 550, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(230, 550, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(230, 505, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 507, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(990, 49, 321, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(1200, 4, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(1130, 390, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(1200, 374, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 600, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(470, 507, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(410, 509, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(610, 505, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(550, 509, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(710, 509, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(760, 505, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(110, 603, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 6, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(250, 6, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(150, 6, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_5.setGeometry(QtCore.QRect(980, 450, 351, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea_5.setFont(font)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 349, 199))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.frame.setGeometry(QtCore.QRect(5, 10, 340, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ch_1 = QtWidgets.QCheckBox(self.frame)
        self.ch_1.setGeometry(QtCore.QRect(70, 10, 54, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.ch_1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_1.setFont(font)
        self.ch_1.setObjectName("ch_1")
        self.ch_2 = QtWidgets.QCheckBox(self.frame)
        self.ch_2.setGeometry(QtCore.QRect(140, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_2.setFont(font)
        self.ch_2.setObjectName("ch_2")
        self.ch_3 = QtWidgets.QCheckBox(self.frame)
        self.ch_3.setGeometry(QtCore.QRect(210, 10, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_3.setFont(font)
        self.ch_3.setObjectName("ch_3")
        self.ch_6 = QtWidgets.QCheckBox(self.frame)
        self.ch_6.setGeometry(QtCore.QRect(170, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_6.setFont(font)
        self.ch_6.setObjectName("ch_6")
        self.ch_4 = QtWidgets.QCheckBox(self.frame)
        self.ch_4.setGeometry(QtCore.QRect(32, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_4.setFont(font)
        self.ch_4.setObjectName("ch_4")
        self.ch_5 = QtWidgets.QCheckBox(self.frame)
        self.ch_5.setGeometry(QtCore.QRect(100, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_5.setFont(font)
        self.ch_5.setObjectName("ch_5")
        self.ch_9 = QtWidgets.QCheckBox(self.frame)
        self.ch_9.setGeometry(QtCore.QRect(68, 80, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_9.setFont(font)
        self.ch_9.setObjectName("ch_9")
        self.ch_8 = QtWidgets.QCheckBox(self.frame)
        self.ch_8.setGeometry(QtCore.QRect(8, 80, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_8.setFont(font)
        self.ch_8.setObjectName("ch_8")
        self.ch_7 = QtWidgets.QCheckBox(self.frame)
        self.ch_7.setGeometry(QtCore.QRect(240, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_7.setFont(font)
        self.ch_7.setObjectName("ch_7")
        self.ch_10 = QtWidgets.QCheckBox(self.frame)
        self.ch_10.setGeometry(QtCore.QRect(130, 80, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_10.setFont(font)
        self.ch_10.setObjectName("ch_10")
        self.ch_12 = QtWidgets.QCheckBox(self.frame)
        self.ch_12.setGeometry(QtCore.QRect(266, 80, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_12.setFont(font)
        self.ch_12.setObjectName("ch_12")
        self.ch_11 = QtWidgets.QCheckBox(self.frame)
        self.ch_11.setGeometry(QtCore.QRect(198, 80, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_11.setFont(font)
        self.ch_11.setObjectName("ch_11")
        self.ch_13 = QtWidgets.QCheckBox(self.frame)
        self.ch_13.setGeometry(QtCore.QRect(32, 115, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_13.setFont(font)
        self.ch_13.setObjectName("ch_13")
        self.ch_14 = QtWidgets.QCheckBox(self.frame)
        self.ch_14.setGeometry(QtCore.QRect(100, 115, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_14.setFont(font)
        self.ch_14.setObjectName("ch_14")
        self.ch_15 = QtWidgets.QCheckBox(self.frame)
        self.ch_15.setGeometry(QtCore.QRect(170, 115, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_15.setFont(font)
        self.ch_15.setObjectName("ch_15")
        self.ch_16 = QtWidgets.QCheckBox(self.frame)
        self.ch_16.setGeometry(QtCore.QRect(240, 115, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_16.setFont(font)
        self.ch_16.setObjectName("ch_16")
        self.ch_17 = QtWidgets.QCheckBox(self.frame)
        self.ch_17.setGeometry(QtCore.QRect(60, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_17.setFont(font)
        self.ch_17.setObjectName("ch_17")
        self.ch_18 = QtWidgets.QCheckBox(self.frame)
        self.ch_18.setGeometry(QtCore.QRect(140, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_18.setFont(font)
        self.ch_18.setObjectName("ch_18")
        self.ch_19 = QtWidgets.QCheckBox(self.frame)
        self.ch_19.setGeometry(QtCore.QRect(210, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ch_19.setFont(font)
        self.ch_19.setObjectName("ch_19")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.pB_save_all_SSD = QtWidgets.QPushButton(self.tab)
        self.pB_save_all_SSD.setGeometry(QtCore.QRect(670, 599, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pB_save_all_SSD.setFont(font)
        self.pB_save_all_SSD.setObjectName("pB_save_all_SSD")
        self.cB_keep_condition = QtWidgets.QCheckBox(self.tab)
        self.cB_keep_condition.setGeometry(QtCore.QRect(1180, 420, 141, 21))
        self.cB_keep_condition.setObjectName("cB_keep_condition")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(1040, 60, 281, 371))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 279, 369))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1180, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_2)
        self.widget_3.setGeometry(QtCore.QRect(220, 90, 761, 541))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 74, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 13, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(190, 10, 631, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 124, 120, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rb_sum = QtWidgets.QRadioButton(self.groupBox)
        self.rb_sum.setGeometry(QtCore.QRect(10, 10, 102, 20))
        self.rb_sum.setObjectName("rb_sum")
        self.rb_avg = QtWidgets.QRadioButton(self.groupBox)
        self.rb_avg.setGeometry(QtCore.QRect(10, 50, 102, 20))
        self.rb_avg.setObjectName("rb_avg")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(1040, 600, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 257, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 224, 51, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 224, 51, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 253, 61, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(1010, 550, 331, 31))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(230, 6, 81, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 6, 71, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 6, 101, 20))
        self.label_10.setObjectName("label_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(1200, 440, 114, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(1040, 445, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_4.setGeometry(QtCore.QRect(1040, 480, 281, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget_5 = QtWidgets.QWidget(self.tab_4)
        self.widget_5.setGeometry(QtCore.QRect(20, 20, 881, 471))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.widget_5.setFont(font)
        self.widget_5.setObjectName("widget_5")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_4.setGeometry(QtCore.QRect(940, 70, 401, 511))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scrollArea_4.setFont(font)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 399, 509))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_13.setGeometry(QtCore.QRect(1080, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_14.setGeometry(QtCore.QRect(1210, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_15.setGeometry(QtCore.QRect(480, 530, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_16.setGeometry(QtCore.QRect(1190, 600, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(610, 540, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.frame_2 = QtWidgets.QFrame(self.tab_4)
        self.frame_2.setGeometry(QtCore.QRect(20, 520, 451, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox.setGeometry(QtCore.QRect(60, 30, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(50000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(60, 70, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(50000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(10, 33, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(10, 71, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(240, 10, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(70, 30, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setMaximum(50000.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(70, 70, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setMaximum(50000.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(20, 36, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(20, 72, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(20, 500, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 10, 991, 621))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.widget_EXAFS = QtWidgets.QWidget(self.tab_6)
        self.widget_EXAFS.setGeometry(QtCore.QRect(10, 10, 571, 401))
        self.widget_EXAFS.setObjectName("widget_EXAFS")
        self.mini_chi_k = QtWidgets.QWidget(self.tab_6)
        self.mini_chi_k.setGeometry(QtCore.QRect(600, 10, 371, 291))
        self.mini_chi_k.setObjectName("mini_chi_k")
        self.mini_FT = QtWidgets.QWidget(self.tab_6)
        self.mini_FT.setGeometry(QtCore.QRect(600, 310, 371, 271))
        self.mini_FT.setObjectName("mini_FT")
        self.frame_3 = QtWidgets.QFrame(self.tab_6)
        self.frame_3.setGeometry(QtCore.QRect(10, 420, 581, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.EXAFSBK_type = QtWidgets.QComboBox(self.frame_3)
        self.EXAFSBK_type.setGeometry(QtCore.QRect(10, 5, 221, 26))
        self.EXAFSBK_type.setObjectName("EXAFSBK_type")
        self.sB_kweight = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.sB_kweight.setGeometry(QtCore.QRect(70, 130, 51, 25))
        self.sB_kweight.setMaximum(3.0)
        self.sB_kweight.setSingleStep(1.0)
        self.sB_kweight.setObjectName("sB_kweight")
        self.double_sB_E0_bk = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.double_sB_E0_bk.setGeometry(QtCore.QRect(290, 5, 101, 25))
        self.double_sB_E0_bk.setDecimals(1)
        self.double_sB_E0_bk.setMaximum(50000.0)
        self.double_sB_E0_bk.setObjectName("double_sB_E0_bk")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(10, 133, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(250, 8, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_8.setGeometry(QtCore.QRect(225, 35, 171, 90))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.double_sB_post_start = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.double_sB_post_start.setGeometry(QtCore.QRect(50, 33, 111, 25))
        self.double_sB_post_start.setDecimals(1)
        self.double_sB_post_start.setMaximum(50000.0)
        self.double_sB_post_start.setObjectName("double_sB_post_start")
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(11, 35, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        self.label_26.setGeometry(QtCore.QRect(11, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(11, 60, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.double_sB_post_end = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.double_sB_post_end.setGeometry(QtCore.QRect(50, 58, 111, 25))
        self.double_sB_post_end.setDecimals(1)
        self.double_sB_post_end.setMaximum(50000.0)
        self.double_sB_post_end.setObjectName("double_sB_post_end")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 35, 211, 90))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.comboBox_preEdge = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_preEdge.setGeometry(QtCore.QRect(95, 5, 111, 26))
        self.comboBox_preEdge.setObjectName("comboBox_preEdge")
        self.double_sB_pre_start = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.double_sB_pre_start.setGeometry(QtCore.QRect(60, 32, 131, 25))
        self.double_sB_pre_start.setDecimals(1)
        self.double_sB_pre_start.setMaximum(50000.0)
        self.double_sB_pre_start.setObjectName("double_sB_pre_start")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(10, 34, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(8, 8, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setGeometry(QtCore.QRect(10, 60, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.double_sB_pre_end = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.double_sB_pre_end.setGeometry(QtCore.QRect(60, 57, 131, 25))
        self.double_sB_pre_end.setDecimals(1)
        self.double_sB_pre_end.setMaximum(50000.0)
        self.double_sB_pre_end.setObjectName("double_sB_pre_end")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(420, 8, 31, 20))
        self.label_28.setObjectName("label_28")
        self.double_sB_rbkg = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.double_sB_rbkg.setGeometry(QtCore.QRect(460, 5, 62, 25))
        self.double_sB_rbkg.setMaximum(2.0)
        self.double_sB_rbkg.setSingleStep(0.05)
        self.double_sB_rbkg.setProperty("value", 1.0)
        self.double_sB_rbkg.setObjectName("double_sB_rbkg")
        self.degree_SS = QtWidgets.QSpinBox(self.frame_3)
        self.degree_SS.setGeometry(QtCore.QRect(190, 130, 53, 25))
        self.degree_SS.setMinimum(1)
        self.degree_SS.setMaximum(5)
        self.degree_SS.setProperty("value", 3)
        self.degree_SS.setObjectName("degree_SS")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(130, 133, 54, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.SmoothF = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.SmoothF.setGeometry(QtCore.QRect(320, 130, 62, 25))
        self.SmoothF.setMaximum(5.0)
        self.SmoothF.setSingleStep(0.05)
        self.SmoothF.setProperty("value", 1.0)
        self.SmoothF.setObjectName("SmoothF")
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setGeometry(QtCore.QRect(260, 133, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(400, 133, 51, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_9.setGeometry(QtCore.QRect(400, 35, 171, 90))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.double_sB_sP_start = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.double_sB_sP_start.setGeometry(QtCore.QRect(50, 33, 111, 25))
        self.double_sB_sP_start.setDecimals(2)
        self.double_sB_sP_start.setMaximum(5.0)
        self.double_sB_sP_start.setSingleStep(0.05)
        self.double_sB_sP_start.setObjectName("double_sB_sP_start")
        self.label_38 = QtWidgets.QLabel(self.groupBox_9)
        self.label_38.setGeometry(QtCore.QRect(11, 35, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_9)
        self.label_39.setGeometry(QtCore.QRect(11, 10, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_9)
        self.label_40.setGeometry(QtCore.QRect(11, 60, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.double_sB_sP_end = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.double_sB_sP_end.setGeometry(QtCore.QRect(50, 58, 111, 25))
        self.double_sB_sP_end.setDecimals(2)
        self.double_sB_sP_end.setMaximum(30.0)
        self.double_sB_sP_end.setSingleStep(0.1)
        self.double_sB_sP_end.setProperty("value", 0.0)
        self.double_sB_sP_end.setObjectName("double_sB_sP_end")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.w_chi_k = QtWidgets.QWidget(self.tab_7)
        self.w_chi_k.setGeometry(QtCore.QRect(50, 80, 841, 501))
        self.w_chi_k.setObjectName("w_chi_k")
        self.frame_5 = QtWidgets.QFrame(self.tab_7)
        self.frame_5.setGeometry(QtCore.QRect(190, 26, 581, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.double_sB_kmin = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.double_sB_kmin.setGeometry(QtCore.QRect(70, 10, 131, 25))
        self.double_sB_kmin.setProperty("value", 3.0)
        self.double_sB_kmin.setObjectName("double_sB_kmin")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(20, 12, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_5)
        self.label_31.setGeometry(QtCore.QRect(220, 12, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.double_sB_kmax = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.double_sB_kmax.setGeometry(QtCore.QRect(270, 10, 131, 25))
        self.double_sB_kmax.setProperty("value", 12.0)
        self.double_sB_kmax.setObjectName("double_sB_kmax")
        self.sB_chi_kw = QtWidgets.QSpinBox(self.frame_5)
        self.sB_chi_kw.setGeometry(QtCore.QRect(500, 10, 53, 25))
        self.sB_chi_kw.setMaximum(3)
        self.sB_chi_kw.setProperty("value", 3)
        self.sB_chi_kw.setObjectName("sB_chi_kw")
        self.label_32 = QtWidgets.QLabel(self.frame_5)
        self.label_32.setGeometry(QtCore.QRect(430, 14, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setGeometry(QtCore.QRect(50, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_21.setGeometry(QtCore.QRect(800, 20, 81, 51))
        self.pushButton_21.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("RightArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_21.setObjectName("pushButton_21")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.w_FT = QtWidgets.QWidget(self.tab_8)
        self.w_FT.setGeometry(QtCore.QRect(10, 40, 831, 531))
        self.w_FT.setObjectName("w_FT")
        self.label_21 = QtWidgets.QLabel(self.tab_8)
        self.label_21.setGeometry(QtCore.QRect(670, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.FT_kweight = QtWidgets.QComboBox(self.tab_8)
        self.FT_kweight.setGeometry(QtCore.QRect(760, 10, 71, 26))
        self.FT_kweight.setObjectName("FT_kweight")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_6.setGeometry(QtCore.QRect(1030, 110, 301, 481))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 299, 479))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_17.setGeometry(QtCore.QRect(1220, 60, 110, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_18.setGeometry(QtCore.QRect(1110, 60, 110, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_19.setGeometry(QtCore.QRect(1190, 600, 141, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_20.setGeometry(QtCore.QRect(1020, 15, 81, 81))
        self.pushButton_20.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("rotate360anticlockwise2red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pB_cp_to_all_EXAFS = QtWidgets.QPushButton(self.tab_5)
        self.pB_cp_to_all_EXAFS.setGeometry(QtCore.QRect(1110, 11, 221, 41))
        self.pB_cp_to_all_EXAFS.setObjectName("pB_cp_to_all_EXAFS")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_52 = QtWidgets.QLabel(self.tab_9)
        self.label_52.setGeometry(QtCore.QRect(570, 512, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.scrollArea_16 = QtWidgets.QScrollArea(self.tab_9)
        self.scrollArea_16.setGeometry(QtCore.QRect(980, 406, 350, 240))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea_16.setFont(font)
        self.scrollArea_16.setWidgetResizable(True)
        self.scrollArea_16.setObjectName("scrollArea_16")
        self.scrollAreaWidgetContents_16 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_16.setGeometry(QtCore.QRect(0, 0, 348, 238))
        self.scrollAreaWidgetContents_16.setObjectName("scrollAreaWidgetContents_16")
        self.scrollArea_16.setWidget(self.scrollAreaWidgetContents_16)
        self.scrollArea_17 = QtWidgets.QScrollArea(self.tab_9)
        self.scrollArea_17.setGeometry(QtCore.QRect(1030, 50, 281, 281))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea_17.setFont(font)
        self.scrollArea_17.setWidgetResizable(True)
        self.scrollArea_17.setObjectName("scrollArea_17")
        self.scrollAreaWidgetContents_17 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_17.setGeometry(QtCore.QRect(0, 0, 279, 279))
        self.scrollAreaWidgetContents_17.setObjectName("scrollAreaWidgetContents_17")
        self.scrollArea_17.setWidget(self.scrollAreaWidgetContents_17)
        self.BL36XU_widget1 = QtWidgets.QWidget(self.tab_9)
        self.BL36XU_widget1.setGeometry(QtCore.QRect(0, 20, 491, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_widget1.setFont(font)
        self.BL36XU_widget1.setObjectName("BL36XU_widget1")
        self.BL36XU_Atom = QtWidgets.QLineEdit(self.tab_9)
        self.BL36XU_Atom.setGeometry(QtCore.QRect(480, 512, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_Atom.setFont(font)
        self.BL36XU_Atom.setObjectName("BL36XU_Atom")
        self.BL36XU_widget2 = QtWidgets.QWidget(self.tab_9)
        self.BL36XU_widget2.setGeometry(QtCore.QRect(520, 20, 441, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_widget2.setFont(font)
        self.BL36XU_widget2.setObjectName("BL36XU_widget2")
        self.BL36XU_textBrowser = QtWidgets.QTextBrowser(self.tab_9)
        self.BL36XU_textBrowser.setGeometry(QtCore.QRect(220, 550, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_textBrowser.setFont(font)
        self.BL36XU_textBrowser.setObjectName("BL36XU_textBrowser")
        self.BL36XU_outpath = QtWidgets.QPushButton(self.tab_9)
        self.BL36XU_outpath.setGeometry(QtCore.QRect(80, 552, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_outpath.setFont(font)
        self.BL36XU_outpath.setObjectName("BL36XU_outpath")
        self.label_53 = QtWidgets.QLabel(self.tab_9)
        self.label_53.setGeometry(QtCore.QRect(80, 510, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.BL36XU_Edge = QtWidgets.QComboBox(self.tab_9)
        self.BL36XU_Edge.setGeometry(QtCore.QRect(630, 510, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_Edge.setFont(font)
        self.BL36XU_Edge.setObjectName("BL36XU_Edge")
        self.BL36XU_Save = QtWidgets.QPushButton(self.tab_9)
        self.BL36XU_Save.setGeometry(QtCore.QRect(480, 600, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_Save.setFont(font)
        self.BL36XU_Save.setObjectName("BL36XU_Save")
        self.BL36XU_RSall = QtWidgets.QPushButton(self.tab_9)
        self.BL36XU_RSall.setGeometry(QtCore.QRect(1200, 340, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_RSall.setFont(font)
        self.BL36XU_RSall.setObjectName("BL36XU_RSall")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_19.setGeometry(QtCore.QRect(110, 604, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.label_54 = QtWidgets.QLabel(self.groupBox_19)
        self.label_54.setGeometry(QtCore.QRect(20, 6, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.BL36XU_rB_Athena = QtWidgets.QRadioButton(self.groupBox_19)
        self.BL36XU_rB_Athena.setGeometry(QtCore.QRect(250, 6, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_rB_Athena.setFont(font)
        self.BL36XU_rB_Athena.setObjectName("BL36XU_rB_Athena")
        self.BL36XU_rB_REX = QtWidgets.QRadioButton(self.groupBox_19)
        self.BL36XU_rB_REX.setGeometry(QtCore.QRect(150, 6, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_rB_REX.setFont(font)
        self.BL36XU_rB_REX.setObjectName("BL36XU_rB_REX")
        self.label_55 = QtWidgets.QLabel(self.tab_9)
        self.label_55.setGeometry(QtCore.QRect(410, 514, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_57 = QtWidgets.QLabel(self.tab_9)
        self.label_57.setGeometry(QtCore.QRect(1120, 350, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.BL36XU_Open = QtWidgets.QPushButton(self.tab_9)
        self.BL36XU_Open.setGeometry(QtCore.QRect(1200, 5, 114, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_Open.setFont(font)
        self.BL36XU_Open.setObjectName("BL36XU_Open")
        self.BL36XU_ST = QtWidgets.QComboBox(self.tab_9)
        self.BL36XU_ST.setGeometry(QtCore.QRect(190, 507, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL36XU_ST.setFont(font)
        self.BL36XU_ST.setObjectName("BL36XU_ST")
        self.pB_save_all_SSD_2 = QtWidgets.QPushButton(self.tab_9)
        self.pB_save_all_SSD_2.setGeometry(QtCore.QRect(640, 600, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pB_save_all_SSD_2.setFont(font)
        self.pB_save_all_SSD_2.setObjectName("pB_save_all_SSD_2")
        self.cB_keep_condition_2 = QtWidgets.QCheckBox(self.tab_9)
        self.cB_keep_condition_2.setGeometry(QtCore.QRect(1140, 380, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cB_keep_condition_2.setFont(font)
        self.cB_keep_condition_2.setObjectName("cB_keep_condition_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_10.setGeometry(QtCore.QRect(170, 460, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.rB_BL36XU = QtWidgets.QRadioButton(self.groupBox_10)
        self.rB_BL36XU.setGeometry(QtCore.QRect(20, 10, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rB_BL36XU.setFont(font)
        self.rB_BL36XU.setChecked(True)
        self.rB_BL36XU.setObjectName("rB_BL36XU")
        self.rB_BL14B1 = QtWidgets.QRadioButton(self.groupBox_10)
        self.rB_BL14B1.setGeometry(QtCore.QRect(130, 10, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rB_BL14B1.setFont(font)
        self.rB_BL14B1.setObjectName("rB_BL14B1")
        self.rB_7elements_SDD = QtWidgets.QRadioButton(self.groupBox_10)
        self.rB_7elements_SDD.setGeometry(QtCore.QRect(230, 10, 141, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rB_7elements_SDD.setFont(font)
        self.rB_7elements_SDD.setObjectName("rB_7elements_SDD")
        self.rB_DUBBLE = QtWidgets.QRadioButton(self.groupBox_10)
        self.rB_DUBBLE.setGeometry(QtCore.QRect(360, 10, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rB_DUBBLE.setFont(font)
        self.rB_DUBBLE.setObjectName("rB_DUBBLE")
        self.label_56 = QtWidgets.QLabel(self.tab_9)
        self.label_56.setGeometry(QtCore.QRect(80, 470, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.tabWidget.addTab(self.tab_9, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Atom:"))
        self.label_9.setText(_translate("MainWindow", "Edge:"))
        self.lineEdit_3.setText(_translate("MainWindow", "Cu"))
        self.pushButton_9.setText(_translate("MainWindow", "Open"))
        self.pushButton_10.setText(_translate("MainWindow", "Output Path"))
        self.pushButton_11.setText(_translate("MainWindow", "Convert"))
        self.radioButton_5.setText(_translate("MainWindow", "REX"))
        self.radioButton_6.setText(_translate("MainWindow", "Athena"))
        self.label_12.setText(_translate("MainWindow", "Save Format"))
        self.checkBox_3.setText(_translate("MainWindow", "Smoothing and Interpolation"))
        self.pushButton_22.setText(_translate("MainWindow", "Open"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Savitzky-Golay"))
        self.label_34.setText(_translate("MainWindow", "Window Size"))
        self.label_36.setText(_translate("MainWindow", "PolyOrder"))
        self.rB_9809.setText(_translate("MainWindow", "9809"))
        self.rB_DUBBLE_2.setText(_translate("MainWindow", "DUBBLE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Transmission&Fluorescense"))
        self.pushButton.setText(_translate("MainWindow", "Output Path"))
        self.label.setText(_translate("MainWindow", "Shaping Time"))
        self.pushButton_2.setText(_translate("MainWindow", "Open"))
        self.label_2.setText(_translate("MainWindow", "Channels"))
        self.pushButton_5.setText(_translate("MainWindow", "Release all"))
        self.pushButton_6.setText(_translate("MainWindow", "Save"))
        self.lineEdit.setText(_translate("MainWindow", "Cu"))
        self.label_3.setText(_translate("MainWindow", "Atom:"))
        self.label_4.setText(_translate("MainWindow", "Edge:"))
        self.label_7.setText(_translate("MainWindow", "BL:"))
        self.label_11.setText(_translate("MainWindow", "Save Format"))
        self.radioButton_2.setText(_translate("MainWindow", "Athena"))
        self.radioButton.setText(_translate("MainWindow", "REX"))
        self.ch_1.setText(_translate("MainWindow", "ch:1"))
        self.ch_2.setText(_translate("MainWindow", "ch:2"))
        self.ch_3.setText(_translate("MainWindow", "ch:3"))
        self.ch_6.setText(_translate("MainWindow", "ch:6"))
        self.ch_4.setText(_translate("MainWindow", "ch:4"))
        self.ch_5.setText(_translate("MainWindow", "ch:5"))
        self.ch_9.setText(_translate("MainWindow", "ch:9"))
        self.ch_8.setText(_translate("MainWindow", "ch:8"))
        self.ch_7.setText(_translate("MainWindow", "ch:7"))
        self.ch_10.setText(_translate("MainWindow", "ch:10"))
        self.ch_12.setText(_translate("MainWindow", "ch:12"))
        self.ch_11.setText(_translate("MainWindow", "ch:11"))
        self.ch_13.setText(_translate("MainWindow", "ch:13"))
        self.ch_14.setText(_translate("MainWindow", "ch:14"))
        self.ch_15.setText(_translate("MainWindow", "ch:15"))
        self.ch_16.setText(_translate("MainWindow", "ch:16"))
        self.ch_17.setText(_translate("MainWindow", "ch:17"))
        self.ch_18.setText(_translate("MainWindow", "ch:18"))
        self.ch_19.setText(_translate("MainWindow", "ch:19"))
        self.pB_save_all_SSD.setText(_translate("MainWindow", "Save all using current"))
        self.cB_keep_condition.setText(_translate("MainWindow", "Keep this condition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "19 SSD"))
        self.pushButton_3.setText(_translate("MainWindow", "Open"))
        self.pushButton_4.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_7.setText(_translate("MainWindow", "Output Path"))
        self.rb_sum.setText(_translate("MainWindow", "Sum"))
        self.rb_avg.setText(_translate("MainWindow", "Average"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "Edge:"))
        self.label_6.setText(_translate("MainWindow", "Atom:"))
        self.lineEdit_2.setText(_translate("MainWindow", "Cu"))
        self.radioButton_4.setText(_translate("MainWindow", "Athena"))
        self.radioButton_3.setText(_translate("MainWindow", "REX"))
        self.label_10.setText(_translate("MainWindow", "Save Format"))
        self.pushButton_12.setText(_translate("MainWindow", "Set"))
        self.label_13.setText(_translate("MainWindow", "To interpolate as:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Interpolation Summation"))
        self.pushButton_13.setText(_translate("MainWindow", "Add"))
        self.pushButton_14.setText(_translate("MainWindow", "Open"))
        self.pushButton_15.setText(_translate("MainWindow", "replot"))
        self.pushButton_16.setText(_translate("MainWindow", "Save"))
        self.checkBox.setText(_translate("MainWindow", "plot ut, bg"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Lower"))
        self.label_14.setText(_translate("MainWindow", "Start"))
        self.label_15.setText(_translate("MainWindow", "End"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Upper"))
        self.label_16.setText(_translate("MainWindow", "Start"))
        self.label_17.setText(_translate("MainWindow", "End"))
        self.label_18.setText(_translate("MainWindow", "Normarization condition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "XANES comparison"))
        self.label_29.setText(_translate("MainWindow", "weight"))
        self.label_20.setText(_translate("MainWindow", "E0"))
        self.label_25.setText(_translate("MainWindow", "Start"))
        self.label_26.setText(_translate("MainWindow", "post edge [eV]"))
        self.label_27.setText(_translate("MainWindow", "End"))
        self.label_22.setText(_translate("MainWindow", "Start"))
        self.label_23.setText(_translate("MainWindow", "pre edge [eV]"))
        self.label_24.setText(_translate("MainWindow", "End"))
        self.label_28.setText(_translate("MainWindow", "rbkg"))
        self.label_33.setText(_translate("MainWindow", "Degree:"))
        self.label_35.setText(_translate("MainWindow", "Factor:"))
        self.checkBox_2.setText(_translate("MainWindow", "opt"))
        self.label_38.setText(_translate("MainWindow", "Start"))
        self.label_39.setText(_translate("MainWindow", "spline range in k [1/Å]"))
        self.label_40.setText(_translate("MainWindow", "End"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "EXAFS"))
        self.label_30.setText(_translate("MainWindow", "k min:"))
        self.label_31.setText(_translate("MainWindow", "k max:"))
        self.label_32.setText(_translate("MainWindow", "k weight"))
        self.label_19.setText(_translate("MainWindow", "FT Conditons"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "chi_k"))
        self.label_21.setText(_translate("MainWindow", "k weight"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "FT"))
        self.pushButton_17.setText(_translate("MainWindow", "Open"))
        self.pushButton_18.setText(_translate("MainWindow", "Add"))
        self.pushButton_19.setText(_translate("MainWindow", "Save"))
        self.pB_cp_to_all_EXAFS.setText(_translate("MainWindow", "Copy Current to All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "EXAFS comparison"))
        self.label_52.setText(_translate("MainWindow", "Edge:"))
        self.BL36XU_Atom.setText(_translate("MainWindow", "Cu"))
        self.BL36XU_outpath.setText(_translate("MainWindow", "Output Path"))
        self.label_53.setText(_translate("MainWindow", "Shaping Time"))
        self.BL36XU_Save.setText(_translate("MainWindow", "Save"))
        self.BL36XU_RSall.setText(_translate("MainWindow", "Release all"))
        self.label_54.setText(_translate("MainWindow", "Save Format"))
        self.BL36XU_rB_Athena.setText(_translate("MainWindow", "Athena"))
        self.BL36XU_rB_REX.setText(_translate("MainWindow", "REX"))
        self.label_55.setText(_translate("MainWindow", "Atom:"))
        self.label_57.setText(_translate("MainWindow", "Channels"))
        self.BL36XU_Open.setText(_translate("MainWindow", "Open"))
        self.pB_save_all_SSD_2.setText(_translate("MainWindow", "Save all using current"))
        self.cB_keep_condition_2.setText(_translate("MainWindow", "Keep this condition"))
        self.rB_BL36XU.setText(_translate("MainWindow", "BL36XU"))
        self.rB_BL14B1.setText(_translate("MainWindow", "BL14B1"))
        self.rB_7elements_SDD.setText(_translate("MainWindow", "7 elements SDD"))
        self.rB_DUBBLE.setText(_translate("MainWindow", "DUBBLE"))
        self.label_56.setText(_translate("MainWindow", "File format:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "36XU,BL14B1,SDD"))

